var construction = {
    "type": "FeatureCollection",
    "features": [

        {"type": "Feature","properties": {"category" : "Construction", "name": "<b><u>Side Walk</b></u>", "description": "<br><br>Hole in sidewalk. Wheelchairs avoid this area."}, "geometry": {"type": "Point","coordinates": [-81.738684, 39.993779]}},
        {"type": "Feature","properties": {"category" : "Construction", "name": "<b><u>Road</b></u>", "description": "<br><br>Tree on road. Cars avoid."}, "geometry": {"type": "Point","coordinates": [-81.739891, 39.999249]}}

    ]
};


var buildings = {
    "type": "FeatureCollection",
    "features": [

        //Academic Buildings
        {"type": "Feature","properties": {"category" : "Academic Buildings", "name": "<b><u>Montgomery Hall</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Level Entry Doors<br>Gender Neutral Bathrooms<br>Lactation Station"}, "geometry": {"type": "Polygon","coordinates": [[[-81.737552, 39.996652], [-81.73752, 39.996417], [-81.73686, 39.996454], [ -81.736881, 39.996693]]]}},
        {"type": "Feature","properties": {"category" : "Academic Buildings", "name": "<b><u>Brown Chapel</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Push Button Door<br>Lactation Station<br>Elevator<br>Gender Neutral Bathroom"}, "geometry": {"type": "Polygon","coordinates": [[[-81.735894, 39.996701], [-81.735878, 39.996532], [-81.736414, 39.996524], [-81.736425, 39.99668]]]}},
        {"type": "Feature","properties": {"category" : "Academic Buildings", "name": "<b><u>Boyd Science Center</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Push Button Doors<br>Level Entry Doors<br>Gender Neutral Bathrooms<br>Elevator"}, "geometry": {"type": "Polygon","coordinates": [[[-81.736967, 39.997005], [-81.737015, 39.997379], [-81.736618, 39.997695], [-81.7362, 39.997408], [-81.736672, 39.997017]]]}},
        {"type": "Feature","properties": {"category" : "Academic Buildings", "name": "<b><u>John Glenn Gym</b></u>", "description": "<br><br><b>Accommodations:</b> <br><br>"}, "geometry": {"type": "Polygon","coordinates": [[[-81.737654, 39.998271],[-81.737112, 39.998295],[-81.737085, 39.997991], [-81.737621, 39.997954]]]}},
        {"type": "Feature","properties": {"category" : "Academic Buildings", "name": "<b><u>Anne C. Steele Recreation Center</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Level Entry Door<br>Push Button Door<br>Elevator<br>Handicap Parking"}, "geometry": {"type": "Polygon","coordinates": [[[ -81.738367, 39.998275],[-81.737648, 39.998312],[-81.737611, 39.997868], [-81.738319, 39.997823]]]}},
        {"type": "Feature","properties": {"category" : "Academic Buildings", "name": "<b><u>Quad Center</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Handicap Parking"}, "geometry": {"type": "Polygon","coordinates": [[[-81.737916, 39.997774],[-81.73768, 39.997782],[-81.737659, 39.997609], [-81.737906, 39.997593]]]}},
        {"type": "Feature","properties": {"category" : "Academic Buildings", "name": "<b><u>Bookstore</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Handicap Parking"}, "geometry": {"type": "Polygon","coordinates": [[[-81.737906, 39.997593], [-81.737772, 39.997601], [-81.737772, 39.997494], [-81.737648, 39.997498], [-81.737638, 39.997408], [-81.737879, 39.997387]]]}},
        {"type": "Feature","properties": {"category" : "Academic Buildings", "name": "<b><u>University Police</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Handicap Parking"}, "geometry": {"type": "Polygon","coordinates": [[[-81.738474, 39.997585],[-81.73834, 39.997593],[-81.738314, 39.997472], [-81.738453, 39.997468]]]}},
        {"type": "Feature","properties": {"category" : "Academic Buildings", "name": "<b><u>Cambridge Hall</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Level Entry Door<br>Push Button Door<br>Elevator<br>Handicap Parking"}, "geometry": {"type": "Polygon","coordinates": [[[-81.737895, 39.997258,],[-81.737616, 39.997275],[-81.737573, 39.996822], [-81.737852, 39.996806]]]}},
        {"type": "Feature","properties": {"category" : "Academic Buildings", "name": "<b><u>Caldwell Hall</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Level Entry Door<br>Push Button Doors<br>Elevator<br>Handicap Parking"}, "geometry": {"type": "Polygon","coordinates": [[[-81.738099, 39.996159],[-81.737927, 39.996172],[-81.737938, 39.996246], [-81.737761, 39.99625], [-81.737766, 39.996344], [-81.737621, 39.996349], [-81.737584, 39.995917], [-81.738062, 39.995881]]]}},
        {"type": "Feature","properties": {"category" : "Academic Buildings", "name": "<b><u>Roberta A. Smith University Library</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Level Entry Door<br>Push Button Door<br>Elevator<br>Gender Neutral Bathroom<br>Handicap Parking"}, "geometry": {"type": "Polygon","coordinates": [[[-81.737375, 39.995451],[-81.737412, 39.995723],[-81.737165, 39.995727], [-81.737171, 39.995764], [-81.736763, 39.995781], [-81.736758, 39.995632], [-81.736844, 39.995624], [-81.736828, 39.995488]]]}},
        {"type": "Feature","properties": {"category" : "Academic Buildings", "name": "<b><u>Walter Hall</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Level Entry Door<br>Push Button Door<br>Elevator"}, "geometry": {"type": "Polygon","coordinates": [[[-81.735277, 39.996195],[-81.735272, 39.995985],[-81.734719, 39.995755], [-81.734623, 39.995866], [-81.735079, 39.99608], [-81.735089, 39.996195]]]}},
        {"type": "Feature","properties": {"category" : "Academic Buildings", "name": "<b><u>Paul Hall</b></u>", "description": "<br><br><b>Accommodations:</b> <br><br>"}, "geometry": {"type": "Polygon","coordinates": [[[-81.734633, 39.995415], [-81.734355, 39.995427],[-81.734344, 39.995299], [-81.734623, 39.995279]]]}},
        {"type": "Feature","properties": {"category" : "Academic Buildings", "name": "<b><u>Neptune Center</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Level Entry Door<br>Push Button Door"}, "geometry": {"type": "Polygon","coordinates": [[[-81.733679, 39.995406],[-81.733657, 39.995217],[-81.733453, 39.995225], [-81.733475, 39.995406]]]}},
        {"type": "Feature","properties": {"category" : "Academic Buildings", "name": "<b><u>Chess Center</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Level Entry Doors<br>Push Button Doors<br>Elevator"}, "geometry": {"type": "Polygon","coordinates": [[[-81.736758, 40.000511],[-81.736463, 40.000581],[-81.73621, 40.000383], [-81.73642, 40.000198], [-81.736709, 40.000392]]]}},
        {"type": "Feature","properties": {"category" : "Academic Buildings", "name": "<b><u>Louis O. Palmer Art Gallery</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Level Entry Door<br>Push Button Door"}, "geometry": {"type": "Polygon","coordinates": [[[-81.734038, 39.99534],[-81.733844, 39.995258],[-81.733909, 39.995163], [-81.734107, 39.995245]]]}},
        {"type": "Feature","properties": {"category" : "Academic Buildings", "name": "<b><u>Wellness Center</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Level Entry Door<br>Handicap Parking"}, "geometry": {"type": "Polygon","coordinates": [[[-81.734071, 39.997687],[-81.733894, 39.997683],[-81.733894, 39.9976], [-81.734065, 39.997604]]]}},


        // Residential Buildings
        {"type": "Feature","properties": {"category" : "Residential Buildings", "name": "<b><u>Kelley Hall</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Level Entry Door<br>Gender Neutral Bathroom<br>Handicap Parking"}, "geometry": {"type": "Polygon","coordinates": [[[-81.736141, 40.000931],[-81.735803, 40.001018],[-81.735744, 40.000919],[-81.735809, 40.000903],[-81.735626, 40.000508], [-81.735524, 40.000443], [-81.735712, 40.000282], [-81.735884, 40.000402], [-81.735787, 40.000492], [-81.735953, 40.000862], [-81.736104, 40.00082]]]}},
        {"type": "Feature","properties": {"category" : "Residential Buildings", "name": "<b><u>Patton Hall</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Level Entry Doors<br>Push Button Doors<br>Elevators<br>Handicap Parking"}, "geometry": {"type": "Polygon","coordinates": [[[-81.73553, 40.000434],[-81.735165, 40.000192],[-81.735326, 40.000032], [-81.735707, 40.000287]]]}},
        {"type": "Feature","properties": {"category" : "Residential Buildings", "name": "<b><u>Finney Hall</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Level Entry Door<br>Push Button Door<br>Elevator<br>Handicap Parking"}, "geometry": {"type": "Polygon","coordinates": [[[-81.734843, 40.000636],[-81.734328, 40.000603],[-81.734328, 40.000451], [-81.734849, 40.000471]]]}},
        {"type": "Feature","properties": {"category" : "Residential Buildings", "name": "<b><u>Moore Hall</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Level Entry Doors<br>Push Button Door<br>Elevator<br>Gender Neutral Bathroom"}, "geometry": {"type": "Polygon","coordinates": [[[-81.738324, 40.000849],[-81.738163, 40.000878],[-81.738018, 40.000467], [-81.738169, 40.000438]]]}},
        {"type": "Feature","properties": {"category" : "Residential Buildings", "name": "<b><u>Memorial Hall</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Level Entry Doors<br>Push Button Doors<br>Elevator<br>Gender Neutral Bathroom"}, "geometry": {"type": "Polygon","coordinates": [[[-81.738684, 40.000237],[-81.738077, 40.00034],[-81.738035, 40.000225], [-81.738635, 40.000114]]]}},
        {"type": "Feature","properties": {"category" : "Residential Buildings", "name": "<b><u>Thomas Hall</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Level Entry Door<br>Psuh Button Door<br>Gender Neutral Bathroom<br>Handicap Parking"}, "geometry": {"type": "Polygon","coordinates": [[[-81.740202, 40.000381],[-81.739907, 40.000276],[-81.739467, 40.000247],[-81.739311, 40.00034], [-81.739182, 40.00025], [-81.73944, 40.000093], [-81.739944, 40.00013], [-81.739939, 40.00004], [-81.740309, 40.00013]]]}},
        {"type": "Feature","properties": {"category" : "Residential Buildings", "name": "<b><u>Town House A</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Level Entry Door<br>Handicap Parking"}, "geometry": {"type": "Polygon","coordinates": [[[-81.742336, 39.999455],[-81.741859, 39.999381],[-81.74188, 39.999295], [-81.742347, 39.999364]]]}},
        {"type": "Feature","properties": {"category" : "Residential Buildings", "name": "<b><u>Town House B</b></u>", "description": "<br><br><b>Accommodations:</b> <br>Level Entry Door<br>Handicap Parking"}, "geometry": {"type": "Polygon","coordinates": [[[-81.741532, 39.999278],[-81.741103, 39.999139],[-81.741156, 39.999052], [-81.741558, 39.9992]]]}},
        {"type": "Feature","properties": {"category" : "Residential Buildings", "name": "<b><u>Ulster House</b></u>", "description": "<br><br><b>Accommodations:</b> <br><br>"}, "geometry": {"type": "Polygon","coordinates": [[[-81.740545, 39.999085],[-81.740384, 39.99911],[-81.740293, 39.998876], [-81.740604, 39.998814], [-81.740647, 39.998925], [-81.740496, 39.998946]]]}},
        {"type": "Feature","properties": {"category" : "Residential Buildings", "name": "<b><u>Stag</b></u>", "description": "<br><br><b>Accommodations:</b> <br><br>"}, "geometry": {"type": "Polygon","coordinates": [[[-81.739762, 39.99851],[-81.739536, 39.998432],[-81.739606, 39.998317], [-81.739821, 39.998387]]]}},
        {"type": "Feature","properties": {"category" : "Residential Buildings", "name": "<b><u>Kappa Sigma</b></u>", "description": "<br><br><b>Accommodations:</b> <br><br>"}, "geometry": {"type": "Polygon","coordinates": [[[-81.741623, 40.001394],[-81.741532, 40.001599],[-81.741377, 40.001554], [-81.741414, 40.001464], [-81.741344, 40.001447], [-81.741398, 40.001336]]]}},
        {"type": "Feature","properties": {"category" : "Residential Buildings", "name": "<b><u>Phi Kappa Tau</b></u>", "description": "<br><br><b>Accommodations:</b> <br><br>"}, "geometry": {"type": "Polygon","coordinates": [[[-81.741554, 40.001016],[-81.741344, 40.00116],[-81.741232, 40.001061], [-81.741312, 40.001008], [-81.74121, 40.000921], [-81.741339, 40.000839]]]}},
        {"type": "Feature","properties": {"category" : "Residential Buildings", "name": "<b><u>MACE</b></u>", "description": "<br><br><b>Accommodations:</b> <br><br>"}, "geometry": {"type": "Polygon","coordinates": [[[-81.741237, 40.001788],[-81.741162, 40.002006],[-81.740851, 40.00194],[-81.740883, 40.001813],[-81.741049, 40.001846],[-81.741076, 40.001755]]]}},
        {"type": "Feature","properties": {"category" : "Residential Buildings", "name": "<b><u>Lakeside Houses</b></u>", "description": "<br><br><b>Accommodations:</b> <br><br>"}, "geometry": {"type": "Polygon","coordinates": [[[-81.73488, 40.000038],[-81.734387, 40.000042],[-81.734258, 39.997572],[-81.7348, 39.997577]]]}},
        {"type": "Feature","properties": {"category" : "Residential Buildings", "name": "<b><u>Kianu Club</b></u>", "description": "<br><br><b>Accommodations:</b> <br><br>"}, "geometry": {"type": "Polygon","coordinates": [[[-81.740357, 39.997889],[-81.740207, 39.997889],[-81.74018, 39.997712],[-81.740336, 39.997704]]]}}


    ]
};

var markers = {
    "type": "FeatureCollection",
    "features": [

      // Handicap Parking
      {"type": "Feature","properties": {"category" : "<img src='images/handicapParkingKEY.png' style='height:2em'/> <span class='my-layer-item'>Handicap Parking</span>", "name": "<b><u>Quad Parking</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.738103, 39.997721]}},
      {"type": "Feature","properties": {"category" : "<img src='images/handicapParkingKEY.png' style='height:2em'/> <span class='my-layer-item'>Handicap Parking</span>", "name": "<b><u>Comin Street Parking</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.738904, 39.997811]}},
      {"type": "Feature","properties": {"category" : "<img src='images/handicapParkingKEY.png' style='height:2em'/> <span class='my-layer-item'>Handicap Parking</span>", "name": "<b><u>Stadium Parking South</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.737304, 39.998773]}},
      {"type": "Feature","properties": {"category" : "<img src='images/handicapParkingKEY.png' style='height:2em'/> <span class='my-layer-item'>Handicap Parking</span>", "name": "<b><u>North of Montgomery</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.737958, 39.996522]}},
      {"type": "Feature","properties": {"category" : "<img src='images/handicapParkingKEY.png' style='height:2em'/> <span class='my-layer-item'>Handicap Parking</span>", "name": "<b><u>East of Montgomery</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.738191, 39.996018]}},
      {"type": "Feature","properties": {"category" : "<img src='images/handicapParkingKEY.png' style='height:2em'/> <span class='my-layer-item'>Handicap Parking</span>", "name": "<b><u>Admission Office</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.7367, 39.996235]}},
      {"type": "Feature","properties": {"category" : "<img src='images/handicapParkingKEY.png' style='height:2em'/> <span class='my-layer-item'>Handicap Parking</span>", "name": "<b><u>Kelley Hall</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.735476, 40.00065]}},
      {"type": "Feature","properties": {"category" : "<img src='images/handicapParkingKEY.png' style='height:2em'/> <span class='my-layer-item'>Handicap Parking</span>", "name": "<b><u>163 Stormont St</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.739811, 40.000294]}},
      {"type": "Feature","properties": {"category" : "<img src='images/handicapParkingKEY.png' style='height:2em'/> <span class='my-layer-item'>Handicap Parking</span>", "name": "<b><u>Townhouses A</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.741315, 39.999015]}},
      {"type": "Feature","properties": {"category" : "<img src='images/handicapParkingKEY.png' style='height:2em'/> <span class='my-layer-item'>Handicap Parking</span>", "name": "<b><u>Townhouses B</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.742274, 39.999255]}},
      {"type": "Feature","properties": {"category" : "<img src='images/handicapParkingKEY.png' style='height:2em'/> <span class='my-layer-item'>Handicap Parking</span>", "name": "<b><u>Caldwell Hall</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.738022, 39.997229]}},
      {"type": "Feature","properties": {"category" : "<img src='images/handicapParkingKEY.png' style='height:2em'/> <span class='my-layer-item'>Handicap Parking</span>", "name": "<b><u>Medical Center</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.734122, 39.997643]}},
      {"type": "Feature","properties": {"category" : "<img src='images/handicapParkingKEY.png' style='height:2em'/> <span class='my-layer-item'>Handicap Parking</span>", "name": "<b><u>Finney Hall</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.734398, 40.000403]}},
      {"type": "Feature","properties": {"category" : "<img src='images/handicapParkingKEY.png' style='height:2em'/> <span class='my-layer-item'>Handicap Parking</span>", "name": "<b><u>Library</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.737217, 39.995447]}},
      {"type": "Feature","properties": {"category" : "<img src='images/handicapParkingKEY.png' style='height:2em'/> <span class='my-layer-item'>Handicap Parking</span>", "name": "<b><u>Thomas Hall</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.73981, 40.000293]}},

      // Level Entry Doors
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Recreation Center)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.737707, 39.997888]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Cambridge Hall)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.73789, 39.997206]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Chess Center E)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.736355, 40.000474]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Ches Center W)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.736661, 40.000404]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Science Center W)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.736967, 39.997322]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Science Center W2)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.736978, 39.997141]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Science Center S)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.736827, 39.997014]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Caldwell Hall)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.737611, 39.99623]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Library)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.737123, 39.995758]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Townhouse A)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.741377, 39.999123]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Townhouse B)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.742045, 39.999308]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Thomas Hall)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.739885, 40.000251]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Kelley Hall)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.735803, 40.000527]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Mem/Moore)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.738228, 40.000424]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Memorial Hall)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.738093, 40.000215]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Moore Hall)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.738230, 40.000838]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Patton Hall W)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.735674, 40.000244]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Patton Hall E)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.735283, 40.000354]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Finney Hall)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.734612, 40.000461]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Healthcare)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.734036, 39.997583]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Walter Hall)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.735197, 39.996035]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Neptune Center)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.733673, 39.995381]}},
      {"type": "Feature","properties": {"category" : "<img src='images/levelEntryDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Level Entry Doors</span>", "name": "<b><u>Level Entry Door (Art Gallery)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.733931, 39.995303]}},


      // Push Button Doors
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Walter Hall)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.735191, 39.996007]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Brown Chapel)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.73642, 39.996584]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Library)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.737128, 39.995766]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Caldwell Hall E)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.737602, 39.996235]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Caldwell Hall W)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.738083, 39.996026]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Cambridge Hall)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.73789, 39.997198]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Recreation Center)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.737664, 39.997884]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Science Center W)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.736967, 39.997316]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Science Center W2)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.736983, 39.997135]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Science Center S)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.736822, 39.997008]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Patton Hall SW)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.735642, 40.000243]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Patton Hall NE)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.735293, 40.000342]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Mem/Moore N)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.738228, 40.000424]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Mem/Moore S)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.738093, 40.00021]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Thomas Hall)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.739885, 40.000256]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Finney Hall)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.734617, 40.000461]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Chess E)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.736368, 40.000468]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Chess W)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.736690, 40.000418]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Art Gallery)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.733936, 39.995303]}},
      {"type": "Feature","properties": {"category" : "<img src='images/pushButtonDoorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Push Button Doors</span>", "name": "<b><u>Push Button Door (Neptune Center)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.733673, 39.995381]}},


      // Lactation Stations
      {"type": "Feature","properties": {"category" : "<img src='images/lactationStationKEY.png' style='height:2em'/> <span class='my-layer-item'>Lactation Stations</span>","name": "<b><u>Lactation Station (Montgomery Hall 1A)</b></u>", "description": "<br><br> To use the room, get the key from Human Resources (Montgomery Hall 16). If after hours, call Campus police ( 740-826-8155 ).  The room has an outlet, seating and a refrigerator for storage of breast milk. It is next to the bathroom."}, "geometry": {"type": "Point","coordinates": [-81.737198, 39.996644]}},
      {"type": "Feature","properties": {"category" : "<img src='images/lactationStationKEY.png' style='height:2em'/> <span class='my-layer-item'>Lactation Stations</span>", "name": "<b><u>Lactation Station (Brown Chapel 18)</b></u>", "description": "<br><br> To use room, ask any nearby professor to unlock. If none available, call Campus police ( 740-826-8155 ).  The room has an outlet and seating. Room does not have a refrigerator for storage of milk at this time. Sink is nearby in lounge area."}, "geometry": {"type": "Point","coordinates": [-81.736162, 39.996694]}},

      // Elevators
      {"type": "Feature","properties": {"category" : "<img src='images/elevatorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Elevators</span>","name": "<b><u>Elevator (Walter Hall)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.735079, 39.996109]}},
      {"type": "Feature","properties": {"category" : "<img src='images/elevatorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Elevators</span>","name": "<b><u>Elevator (Library)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.737117, 39.99559]}},
      {"type": "Feature","properties": {"category" : "<img src='images/elevatorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Elevators</span>","name": "<b><u>Elevator (Caldwell Hall)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.737659, 39.996154]}},
      {"type": "Feature","properties": {"category" : "<img src='images/elevatorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Elevators</span>","name": "<b><u>Elevator (Brown Chapel)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.73635, 39.996639]}},
      {"type": "Feature","properties": {"category" : "<img src='images/elevatorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Elevators</span>","name": "<b><u>Elevator (Science Center)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.736613, 39.997198]}},
      {"type": "Feature","properties": {"category" : "<img src='images/elevatorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Elevators</span>","name": "<b><u>Elevator (Cambridge Hall)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.737643, 39.997116]}},
      {"type": "Feature","properties": {"category" : "<img src='images/elevatorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Elevators</span>","name": "<b><u>Elevator (Recreation Center)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.737734, 39.998198]}},
      {"type": "Feature","properties": {"category" : "<img src='images/elevatorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Elevators</span>","name": "<b><u>Elevator (Finney Hall)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.734591, 40.000591]}},
      {"type": "Feature","properties": {"category" : "<img src='images/elevatorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Elevators</span>","name": "<b><u>Elevator (Patton Hall NW)</b></u> ", "description": "<br><br> Located on first floor just past the dining hall."}, "geometry": {"type": "Point","coordinates": [-81.735535, 40.000369]}},
      {"type": "Feature","properties": {"category" : "<img src='images/elevatorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Elevators</span>","name": "<b><u>Elevator (Patton Hall SE)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.735368, 40.000301]}},
      {"type": "Feature","properties": {"category" : "<img src='images/elevatorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Elevators</span>","name": "<b><u>Elevator (Chess Center)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.736522, 40.000435]}},
      {"type": "Feature","properties": {"category" : "<img src='images/elevatorsKEY.png' style='height:2em'/> <span class='my-layer-item'>Elevators</span>","name": "<b><u>Elevator (Mem/Moore)</b></u>", "description": ""}, "geometry": {"type": "Point","coordinates": [-81.738099, 40.000344]}},


      // Gender Neutral Bathrooms
      {"type": "Feature","properties": {"category" : "<img src='images/genderNeutralBathroomsKEY.png' style='height:2em'/> <span class='my-layer-item'>Gender Neutral Bathrooms</span>", "name": "<b><u>Gender Neutral Bathroom (Boyd Science Center)</b></u>", "description": "<br><br> Located on the 4th floor."}, "geometry": {"type": "Point","coordinates": [-81.736661, 39.997388]}},
      {"type": "Feature","properties": {"category" : "<img src='images/genderNeutralBathroomsKEY.png' style='height:2em'/> <span class='my-layer-item'>Gender Neutral Bathrooms</span>", "name": "<b><u>Gender Neutral Bathroom (Brown Chapel)</b></u>", "description": "<br><br> Located in the basement, near the elevator."}, "geometry": {"type": "Point","coordinates": [-81.736162, 39.996694]}},
      {"type": "Feature","properties": {"category" : "<img src='images/genderNeutralBathroomsKEY.png' style='height:2em'/> <span class='my-layer-item'>Gender Neutral Bathrooms</span>", "name": "<b><u>Gender Neutral Bathroom (Library)</b></u>", "description": "<br><br> Located in the main foyer."}, "geometry": {"type": "Point","coordinates": [-81.737096, 39.995671]}},
      {"type": "Feature","properties": {"category" : "<img src='images/genderNeutralBathroomsKEY.png' style='height:2em'/> <span class='my-layer-item'>Gender Neutral Bathrooms</span>", "name": "<b><u>Gender Neutral Bathrooms (Montgomery Hall E)</b></u>", "description": "<br><br> Located at the top of stairs on the east side of building."}, "geometry": {"type": "Point","coordinates": [-81.736919, 39.996559]}},
      {"type": "Feature","properties": {"category" : "<img src='images/genderNeutralBathroomsKEY.png' style='height:2em'/> <span class='my-layer-item'>Gender Neutral Bathrooms</span>", "name": "<b><u>Gender Neutral Bathrooms (Montgomery Hall W)</b></u>", "description": "<br><br> Located at the top of stairs on the west side of building."}, "geometry": {"type": "Point","coordinates": [-81.737471, 39.996532]}},
      {"type": "Feature","properties": {"category" : "<img src='images/genderNeutralBathroomsKEY.png' style='height:2em'/> <span class='my-layer-item'>Gender Neutral Bathrooms</span>", "name": "<b><u>Gender Neutral Bathroom (Kelley Hall)</b></u>", "description": "<br><br> Located on bottom floor across from the laundry room."}, "geometry": {"type": "Point","coordinates": [-81.735647, 40.000466]}},
      {"type": "Feature","properties": {"category" : "<img src='images/genderNeutralBathroomsKEY.png' style='height:2em'/> <span class='my-layer-item'>Gender Neutral Bathrooms</span>", "name": "<b><u>Gender Neutral Bathroom (Memorial Hall)</b></u>", "description": "<br><br> Ground floor lobby (Moore is connected to Memorial)."}, "geometry": {"type": "Point","coordinates": [-81.738056, 40.000399]}},
      {"type": "Feature","properties": {"category" : "<img src='images/genderNeutralBathroomsKEY.png' style='height:2em'/> <span class='my-layer-item'>Gender Neutral Bathrooms</span>", "name": "<b><u>Gender Neutral Bathroom (Thomas Hall)</b></u>", "description": "<br><br> Ground floor lobby."}, "geometry": {"type": "Point","coordinates": [-81.739869, 40.000206]}}


    ]
};